export const KEY_STORAGE = {
  BIOMETRIC: 'BIOMETRIC',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  DEVICE_TOKEN: 'DEVICE_TOKEN',
  IS_SET_TOKEN: 'IS_SET_TOKEN',
  LAST_OPENED: 'LAST_OPENED',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  FCM_TOKEN: 'FCM_TOKEN',
  LOCALE: 'LOCALE',
}
