export const KEY_STORAGE = {
  BIOMETRIC: 'BIOMETRIC',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  POPUP_PROMOTION: 'POPUP_PROMOTION',
  SHOWED_POP_PROMOTION: 'SHOWED_POP_PROMOTION',
  DEVICE_TOKEN: 'DEVICE_TOKEN',
  IS_SET_TOKEN: 'IS_SET_TOKEN',
  LAST_OPENED: 'LAST_OPENED',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  GPS_X: 'GPS_X',
  GPS_Y: 'GPS_Y',
  FCM_TOKEN: 'FCM_TOKEN',
  LOCALE: 'LOCALE',
};
