const DEFAULT_PREFIX_FONT_FAMILY = 'OpenSans';

//Font-Family
export const FontFamily = {
  LIGHT: `${DEFAULT_PREFIX_FONT_FAMILY}-Light`, //300
  REGULAR: `${DEFAULT_PREFIX_FONT_FAMILY}-Regular`, //400
  MEDIUM: `${DEFAULT_PREFIX_FONT_FAMILY}-Medium`, //500
  SEMI_BOLD: `${DEFAULT_PREFIX_FONT_FAMILY}-SemiBold`, //600
  BOLD: `${DEFAULT_PREFIX_FONT_FAMILY}-Bold`, //700
  EXTRA_BOLD: `${DEFAULT_PREFIX_FONT_FAMILY}-ExtraBold`, //800
  ITALIC: `${DEFAULT_PREFIX_FONT_FAMILY}-Italic`,
};
